// production-ui.js - Etapa 5: interfaz de producción y conexión real con ManuCore
const ProductionUI={
 init(){if(typeof ProductionSystem==='undefined')return;this.mount();const b=document.getElementById('btn-manufacture');if(b)b.onclick=e=>{e.preventDefault();this.startFromDesigner()};this.render()},
 currentDevice(){if(typeof ManuCore==='undefined')return null;const name=document.getElementById('device-name')?.value?.trim()||'Producto Nexus';const type=document.getElementById('device-type')?.value||'smartphone';const price=Number(document.getElementById('device-price')?.value||0);const found=(ManuCore.state.devices||[]).find(d=>d.name===name||d.type===type);if(found)return found;const map={smartphone:'phone_basic',tablet:'tablet_basic',laptop:'laptop_ultrabook'};return{id:'draft_'+Date.now(),name,type:map[type]||type,price,marketValue:price,specs:{}}},
 startFromDesigner(){const device=this.currentDevice();if(!device){UI.notify('Sin producto','Diseña un dispositivo antes de fabricar.','error');return}const companyId=typeof Corporate!=='undefined'&&Corporate.state.subsidiaries[0]?Corporate.state.subsidiaries[0].id:'nexuscorp';const qty=Math.max(1,Number(prompt('¿Cuántas unidades quieres producir?','1000'))||0);if(!qty)return;const r=ProductionSystem.placeOrder(device,qty,companyId);if(!r.ok){UI.notify('Producción no iniciada',r.error,'error');return}UI.notify('🏭 Orden creada',`${device.name}: ${qty.toLocaleString()} unidades programadas.`,'success');this.render()},
 mount(){if(document.getElementById('production-stage5'))return;const host=document.getElementById('tab-fabrica');if(!host)return;const box=document.createElement('div');box.id='production-stage5';box.className='glass-card mt-4';box.innerHTML='<h3>🏭 Producción Industrial</h3><div id="prod5-factories"></div><h4>Órdenes activas</h4><div id="prod5-orders"></div><h4>Productos terminados</h4><div id="prod5-stock"></div>';host.appendChild(box)},
 render(){const f=document.getElementById('prod5-factories'),o=document.getElementById('prod5-orders'),s=document.getElementById('prod5-stock');if(!f||typeof ProductionSystem==='undefined')return;f.innerHTML=ProductionSystem.state.factories.map(x=>`<div class="stat-row"><span>${this.esc(x.name)}</span><span>N${x.level} · ${x.capacityPerMonth.toLocaleString()}/mes · ${Math.round(x.efficiency*100)}% eficiencia</span></div>`).join('')||'<div class="empty-msg">Sin fábricas.</div>';o.innerHTML=ProductionSystem.state.orders.filter(x=>x.status!=='completed').map(x=>`<div class="stat-row"><span>${this.esc(x.deviceName)}</span><span>${(x.quantity-x.remaining).toLocaleString()}/${x.quantity.toLocaleString()} · ${x.status}</span></div>`).join('')||'<div class="empty-msg">No hay órdenes activas.</div>';const e=Object.entries(ProductionSystem.state.inventory);s.innerHTML=e.map(([id,n])=>`<div class="stat-row"><span>${this.esc(id)}</span><span>${Number(n).toLocaleString()}</span></div>`).join('')||'<div class="empty-msg">No hay producto terminado.</div>'},
 esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
};
